### ISSUE TITLE
Fix /api/manga & /api/chapter

### ISSUE THREAD

**Issue by tapnisu** [DjDeveloperr/Manga#1] opened 2022-10-18 14:31 UTC
When sending request to <https://manga.deno.dev/api/search?q=Gabriel%20DropOut> (or any other query) getting error:

```json
{
  "error": "FetchError: 403 (Forbidden)"
}
```

**Comment by DjDeveloperr** [comment] 2022-10-19 11:41
They must have changed something. This project hasn't been updated for a while so that's pretty expected. I'll look into it in free time

**Comment by tapnisu** [comment] 2022-10-23 10:45
I have an idea how I can fix /api/manga & /api/chapter

Url for manga now currently is <https://chapmanganato.com/manga-sy970181>, where 970181 is 951357 + 18824 manga id. I still don't know what "sy" means

Maybe we can give this weird id as an id for params

**Comment by tapnisu** [comment] 2022-10-23 10:53
for /api/chapter: https://manga-proxy.deno.dev is down :(

**Comment by DjDeveloperr** [comment] 2022-10-23 13:08
Seems like we can't just fake headers to fetch images anymore..

**Comment by DjDeveloperr** [comment] 2022-10-23 13:35
Got the proxy working again

**Comment by DjDeveloperr** [comment] 2022-10-24 03:30
API and site are working fine for me now.
I have confirmed that the MangaNato site is just completely closed in some regions, Deno Deploy's North Asia datacenter was one of those. Since Deno Deploy runs code near the user, the request must be going to one of such datacenters.
I think we'd have to host this site somewhere else where region is constant and provides consistent results everywhere in the world.
As this isn't a problem with this project itself, I'll close this issue

**Closed as completed** 2022-10-24 03:31 UTC
